### ISSUE TITLE
Compatibility with Python 2.7.1

### ISSUE THREAD

**Issue by dhruvasagar** [ledzgio/Categorise-Deluge-plugin#1]
Hi,

I just tried to install your plugin, but deluge is unable to load it. I have python 2.7.1 installed on my system and I believe that is the cause of the problem. Please let me know how this can be handled.

Thanks & Regards,
Dhruva Sagar

**Comment by gutenye** [comment]
+1. I need this, too

**Comment by bigsexy420** [comment]
Hopefully I'm not outta line here posting this but I was having this same issue while trying to set up a new Media server with ubuntu. Below are the steps I used to fix the issue hopefully it helps someone else

-remove any Categorise eggs you have in the .config/deluge/plugins folder
-download and install the setuptools python module from here: http://pypi.python.org/pypi/setuptools
- once setuptools has been installed download and extract the source code to a folder in your home directory
- cd into the folder you just downloaded the source code to and run: 
  python setup.py bdist_egg
- the newly created egg file will be located in the dist folder move it from there to the ~/,config/deluge/plugins folder

If you are running a deluge daemon you will need to restart the daemon before it will showup

Hopefully this helps someone else out. If I shouldnt have posted this here or this isnt how it should be done then please let me know so I can learn from my mistakes

Thanks

**Comment by ledzgio** [comment]
Sorry guys I have abandoned this plugin since now. I have some little changes, compiled with python 2.7.3 and it working fine with deluge 1.3.6. I haven't tried with pythin 2.7.1 but it should be the same.

Let me know if anyone have other issues.
